### ISSUE TITLE
When API Key is recycled and 403s are returned, the library returns a KeyError

### ISSUE THREAD

**Issue by cardonator** [GearPlug/activecampaign-python#11]
Relevant traceback:
```
 File "/usr/local/lib/python3.8/site-packages/activecampaign/contacts.py", line 16, in create_a_contact
    return self.client._post("/contacts", json=data)
  File "/usr/local/lib/python3.8/site-packages/activecampaign/client.py", line 37, in _post
    return self._request('POST', endpoint, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/activecampaign/client.py", line 54, in _request
    return self._parse(requests.request(method, self.BASE_URL + endpoint, headers=_headers, **kwargs))
  File "/usr/local/lib/python3.8/site-packages/activecampaign/client.py", line 57, in _parse
    if 'application/json' in response.headers['Content-Type']:
  File "/usr/local/lib/python3.8/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-type'
```
If the API returns a 403 response, the library should return an error response or throw an Exception indicating a Forbidden status.

**Comment by alecamilla** [comment]
A mi me paso algo parecido:
Traceback (most recent call last):
  File "reporteCantContactosListaBD.py", line 463, in <module>
    detalle = procesarJson(username,ip)
  File "reporteCantContactosListaBD.py", line 273, in procesarJson
    response = client.contacts.list_all_contacts(status=estado,listid=idLista,limit=1)
  File "/usr/local/lib/python3.6/site-packages/activecampaign/contacts.py", line 94, in list_all_contacts
    return self.client._get("/contacts", params=params)
  File "/usr/local/lib/python3.6/site-packages/activecampaign/client.py", line 34, in _get
    return self._request('GET', endpoint, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/activecampaign/client.py", line 54, in _request
    return self._parse(requests.request(method, self.BASE_URL + endpoint, headers=_headers, **kwargs))
  File "/usr/local/lib/python3.6/site-packages/activecampaign/client.py", line 57, in _parse
    if 'application/json' in response.headers['Content-Type']:
  File "/usr/local/lib/python3.6/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-type'

Lo resolvi agregando:
try:
  client = Client(CFG._urlNube,CFG._v3_api_key)
   try: 
        response = client.contacts.list_all_contacts(status=estado,listid=idLista,limit=1)
   except AttributeError:
       pass
       ....
except AttributeError:
       pass
       ...

**Comment by pkshahid** [comment]
> Relevant traceback:
> 
> ```
>  File "/usr/local/lib/python3.8/site-packages/activecampaign/contacts.py", line 16, in create_a_contact
>     return self.client._post("/contacts", json=data)
>   File "/usr/local/lib/python3.8/site-packages/activecampaign/client.py", line 37, in _post
>     return self._request('POST', endpoint, **kwargs)
>   File "/usr/local/lib/python3.8/site-packages/activecampaign/client.py", line 54, in _request
>     return self._parse(requests.request(method, self.BASE_URL + endpoint, headers=_headers, **kwargs))
>   File "/usr/local/lib/python3.8/site-packages/activecampaign/client.py", line 57, in _parse
>     if 'application/json' in response.headers['Content-Type']:
>   File "/usr/local/lib/python3.8/site-packages/requests/structures.py", line 54, in __getitem__
>     return self._store[key.lower()][1]
> KeyError: 'content-type'
> ```
> 
> If the API returns a 403 response, the library should return an error response or throw an Exception indicating a Forbidden status.

Did you solve it?
