### ISSUE TITLE
JSONDecodeError on most methods

### ISSUE THREAD

**Issue by duffpop** [GearPlug/activecampaign-python#7]
Hello, I'm receiving the following error on the below methods:

Error:
```Traceback (most recent call last):
  File "/Users/user/Desktop/github/ac_project/main.py", line 49, in <module>
    response = ac_client.contacts.create_a_contact(data)
  File "/Users/user/Desktop/github/ac_project/venv/lib/python3.8/site-packages/activecampaign/contacts.py", line 16, in create_a_contact
    return self.client._post("/contacts", json=data)
  File "/Users/user/Desktop/github/ac_project/venv/lib/python3.8/site-packages/activecampaign/client.py", line 37, in _post
    return self._request('POST', endpoint, **kwargs)
  File "/Users/user/Desktop/github/ac_project/venv/lib/python3.8/site-packages/activecampaign/client.py", line 54, in _request
    return self._parse(requests.request(method, self.BASE_URL + endpoint, headers=_headers, **kwargs))
  File "/Users/user/Desktop/github/ac_project/venv/lib/python3.8/site-packages/activecampaign/client.py", line 58, in _parse
    r = response.json()
  File "/Users/user/Desktop/github/ac_project/venv/lib/python3.8/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Methods tried:
```
list_all_contacts
retrieve_a_contact
create_a_contact
list_all_contacts(email="human@example.com")
```

Sample code:
```
data = {
    "contact": {
        "email": "johndoe@example.com",
        "firstName": "John",
        "lastName": "Doe",
        "phone": "7223224241"
    }
}
response = ac_client.contacts.create_a_contact(data)
```

Any idea what this could be, something with my env perhaps?

**Comment by flp9001** [comment]
I was facing the same issue. 
Was in fact a problem with my env:

I was using the URL like URL should be:

https://xxxxxx.api-us1.com/api/3

but it should be just:


`
URL = "https://xxxxxx.api-us1.com"
from activecampaign.client import Client
client = Client(URL, API_KEY)
`
